/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocioConnect.module.css";

function IssueForm() {
  return (
    <form className={styles.formWrapper}>
      <div className={styles.inputField}>
        <label htmlFor="citizenName">
          Name of citizen <span className={styles.requiredField}>*</span>
        </label>
        <input id="citizenName" className={styles.input} type="text" required />
      </div>
      <div className={styles.inputField}>
        <label htmlFor="emailId">
          Email id<span className={styles.requiredField}>*</span>
        </label>
        <input id="emailId" className={styles.input} type="email" required />
      </div>
      <div className={styles.inputField}>
        <label htmlFor="issueName">
          Issue name<span className={styles.requiredField}>*</span>
        </label>
        <input id="issueName" className={styles.input} type="text" required />
      </div>
      <div className={styles.selectField}>
        <label htmlFor="department" className={styles.label}>
          Issue related department{" "}
          <span className={styles.requiredField}>*</span>
        </label>
        <div className={styles.select}>
          <select id="department" className={styles.selectValue} required>
            <option value="NHAI">
              National Highways Authority of India (NHAI)
            </option>
          </select>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a819a5860a79b746c6f3cd6b829d5d29c2d8884cea526c376dfe491e7253a5b6?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48"
            className={styles.selectIcon}
            alt=""
          />
        </div>
      </div>
      <div className={styles.textareaField}>
        <label htmlFor="issueDescription" className={styles.label}>
          Issue description <span className={styles.requiredField}>*</span>
        </label>
        <textarea id="issueDescription" className={styles.textarea} required>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c095b3d85aeea067dcde1b5e80aa5fff6053475ff4534c96008246c33fa4dc1e?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48"
            className={styles.textareaIcon}
            alt=""
          />
        </textarea>
      </div>
      <button type="button" className={styles.uploadButton}>
        upload File
      </button>
      <button type="submit" className={styles.submitButton}>
        Raise issue
      </button>
    </form>
  );
}

export default IssueForm;
