/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginForm.module.css";

function LoginForm() {
  return (
    <form className={styles.loginForm}>
      <div className={styles.inputGroup}>
        <label htmlFor="email" className={styles.label}>
          Email
        </label>
        <input type="email" id="email" className={styles.input} required />
      </div>
      <div className={styles.inputGroup}>
        <label htmlFor="password" className={styles.label}>
          Password
        </label>
        <input
          type="password"
          id="password"
          className={styles.input}
          required
        />
      </div>
      <div className={styles.buttonGroup}>
        <button type="submit" className={styles.signInButton}>
          Sign In
        </button>
      </div>
      <a href="#forgot-password" className={styles.forgotPassword}>
        Forgot password?
      </a>
    </form>
  );
}

export default LoginForm;
