/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocioConnect.module.css";

function RegisterForm() {
  const formFields = [
    { name: "firstname", label: "Firstname" },
    { name: "lastname", label: "Lastname" },
    { name: "email", label: "Email address", type: "email" },
    { name: "mobile", label: "Mobile Number", type: "tel" },
    { name: "username", label: "Username" },
    { name: "password", label: "Password", type: "password" },
  ];

  return (
    <form className={styles.formContainer}>
      {formFields.map((field, index) => (
        <div key={index} className={styles.formField}>
          <label htmlFor={field.name} className={styles["visually-hidden"]}>
            {field.label}
          </label>
          <input
            type={field.type || "text"}
            id={field.name}
            name={field.name}
            placeholder={field.label}
            className={styles.formInput}
            required
          />
        </div>
      ))}
      <button type="submit" className={styles.submitButton}>
        Register
      </button>
    </form>
  );
}

export default RegisterForm;
